apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-application
  namespace: dev
  labels:
    app: wil42-application
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wil42-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: wil42-application
    spec:
      containers:
      - name: wil42-application
        image: wil42/playground:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
